apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: chatbot2-may1-3
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/maysunfaisal/chatbot2-may1-3:e91888b3a0867b516513f599605b76472d4160ba@sha256:6b4b34d45760ea365555e3303ed8a367f58afb33db82ebd391d214416aec2d76 # use pre-built to bootstrap
          name: app-inference
